# helm repo add grafana https://grafana.github.io/helm-charts
# helm install loki grafana/loki --values values.yaml --version 6.29.0

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
      enabled: true
  limits_config:
    volume_enabled: true
    retention_period: 120h
  ruler:
    enable_api: true
  querier:
    max_concurrent: 2

  storage:
    bucketNames:
      chunks: loki-chunk
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      s3: ${LOKI_S3}
      endpoint: ${LOKI_S3_ENDPOINT}
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: true

    memberlistConfig:
      bind_addr: ['127.0.0.1']

monitoring:
  selfMonitoring:
    enabled: false


minio:
  enabled: false

chunksCache:
  writebackSizeLimit: 20MB
  resources:
    limits:
      memory: 2Gi

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enableStatefulSetAutoDeletePVC: true
    enabled: true
    size: 5Gi
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: LOKI_S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: loki-s3-endpoint
    - name: LOKI_S3
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: loki-s3

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

lokiCanary:
  enabled: false

test:
  enabled: false