apiVersion: "metallb.io/v1beta1"
kind: L2Advertisement
metadata:
  name: metallb-l2-ip
  namespace: metallb-system
---
apiVersion: "metallb.io/v1beta1"
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses: ["172.27.180.1-172.27.180.100"]