# helm repo add nfs-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
# helm install nfs-provisioner nfs-provisioner/nfs-subdir-external-provisioner --values values.yaml --namespace kube-system


nfs:
  server: nfs.proxmox.homelab
  path: /home/devops/nfs_share/kubernetes

storageClass:
  defaultClass: true